apiVersion: apps/v1
kind: Deployment
metadata:
  name: boj-jandi-webapp
  namespace: boj-jandi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boj-jandi-webapp
  template:
    metadata:
      labels:
        app: boj-jandi-webapp
    spec:
      containers:
      - name: webapp
        image: shinkeonkim/boj-jandi:latest
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: boj-jandi-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: boj-jandi-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: boj-jandi-secret
              key: POSTGRES_DB
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: boj-jandi-config
              key: DATABASE_HOST
        - name: DATABASE_PORT
          valueFrom:
            configMapKeyRef:
              name: boj-jandi-config
              key: DATABASE_PORT
